-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgL05SrfwVj/EAbi5Q
sXLrrALs3KivkAMUf3uIoSzWXzCgCgYIKoZIzj0DAQehRANCAASgu1orxrs8YNzm
M97UBX4RjRANiHO1zg0O1CE8NNnpAXPiiq92AF+AAfYNZPwqNqR5peMh6XFmHYYh
xQGVZ0vp
-----END PRIVATE KEY-----